### ISSUE TITLE
Purescript 0.8.3 thinks unfoldableMaybeZipper is an orphan instance

### ISSUE THREAD

**Issue by rgrempel** [DavidHarrison/purescript-list-zipper#1]
First of all, thanks for this module -- much appreciated!

I was using it with Purescript 0.8.3, and it complained that `unfoldableMaybeZipper` was an orphan instance (which it does not allow). Now, just looking at it, I wonder whether this is a compiler bug? Because the instance definition does refer to `Zipper`, and we're in the file that defines `Zipper`. But, I may be misunderstanding.

In any event, I wanted to draw this to your attention. For my own purposes, I've just deleted that instance, since I didn't need it:

https://github.com/rgrempel/purescript-list-zipper/commit/275407b01431fa40bc990bcefa2835ea851f3969

However, there may be a better fix -- or, in fact, if it's a compiler bug then I suppose that one could make an issue for the compiler.

**Comment by DavidHarrison** [comment]
Thanks! I think this is the expected behaviour of the compiler since [v.0.7.3](https://github.com/purescript/purescript/releases/tag/v0.7.3), though I haven't yet found a good way to fix it. You're solution looks to like the best. Do you mind submitting a pull request?

**Comment by rgrempel** [comment]
Sure, I could do that. Would you like me to also fix various warnings that Purescript 0.8.3 emits? I'd be happy to do that, but in some cases it would break back-compatibility (for Purescript versions < 0.8.3).
