### ISSUE TITLE
Bump version for 0.9

### ISSUE THREAD

**Issue by soupi** [DavidHarrison/purescript-list-zipper#5]
Hi,

Can you bump the version for this so it can be installed from bower?
Thanks :)

**Comment by soupi** [comment]
please?

**Comment by DavidHarrison** [comment]
Sorry, I've been a bit busy, I'll try to get to it this evening. Thanks for
reminding me

**Comment by DavidHarrison** [comment]
Still working on it, sorry!

**Comment by felixSchl** [comment]
I am also interested in a release
